### ISSUE TITLE
BadMethodCallException

### ISSUE THREAD

**Issue by jessiesiat** [AltThree/Locker#16]
Checking only for cacheable HTTP methods with Symfony\Component\HttpFoundation\Request::isMethodSafe()

called in LockingMiddleware.php

```
if ($request->isMethodSafe() || $this->shouldPassThrough($request)) {
       return $next($request);
}
```

--------------------------

Question: In what possible scenario are you using this package?

**Comment by jessiesiat** [comment]
Follow up question: In what possible scenario are you using this package?

**Comment by xkrupa12** [comment]
Running into the same issue, have you found solution to it? Thanks

**Comment by jessiesiat** [comment]
not yet, I ended up on removing this from my project as dependency.  :)

**Comment by blitux** [comment]
Hi there!

I'm getting the same error on Laravel 5.7.28 and Locker v4.1.0. I've been doing a little research, but a piece of code got me wondering... what is this for?

I tracked the exception to these lines:

`alt-three/locker/src/Http/Middleware/LockingMiddleware.php:67-69`

```php
        if ($request->isMethodSafe() || $this->shouldPassThrough($request)) {
            return $next($request);
        }
```
Which is ok, because we don't want to lock safe methods (GET, HEAD, OPTIONS, TRACE, these don't suppose to change things on the server side, they SHOULD just return info, this is expected.)

So, `$request->isMethodSafe()` is called here, and lead me to `symfony/http-foundation/Request.php:1435-1452`, on symfony/http-foundation package v4.2.7:

```php
    /**
     * Checks whether or not the method is safe.
     *
     * @see https://tools.ietf.org/html/rfc7231#section-4.2.1
     *
     * @param bool $andCacheable Adds the additional condition that the method should be cacheable. True by default.
     *
     * @return bool
     */
    public function isMethodSafe(/* $andCacheable = true */)
    {
        if (!\func_num_args() || func_get_arg(0)) {
            // setting $andCacheable to false should be deprecated in 4.1
            throw new \BadMethodCallException('Checking only for cacheable HTTP methods with Symfony\Component\HttpFoundation\Request::isMethodSafe() is not supported.');
        }

        return \in_array($this->getMethod(), ['GET', 'HEAD', 'OPTIONS', 'TRACE']);
    }
```
The conditional here is to check if we're calling `isMethodSafe` method with an argument to check for cacheable request method, which is deprecated from 4.1 (there is actually another method to check if a request is cacheable).

So, the argument is never passed onto the method (which should be expected), `func_num_args()` returns `0`, and then negated, so we get `true` from the first part of the conditional, and then we get inside the conditional and the exception is thrown. WTF.

Am I missing something? Because if not, this is a bug on symfony/http-foundation v4.2.7 and we should report it upstream.

**Comment by blitux** [comment]
Heads up! I've updated the report on http-foundation. It seems like isMethodSafe() required an argument to not throw an exception. This should have been deprecated on 4.1 but it was not. 

I don't know how long it will take until it get fixed on http-foundation. In the meantime, can you mantainers change from this `$request->isMethodSafe()` to this `$request->isMethodSafe(false)` in order to avoid the exception?

**Comment by GrahamCampbell** [comment]
Hmmm, yes. Symfony seem to have made a mess of this.

**Comment by blitux** [comment]
Hi there @GrahamCampbell, this issue with isMethodSafe() was fixed on symfony/http-foundation:^4.4. So there's no way that fix can make it to the code. Locker is depending on laravel, which is depending on symfony/http-foundation:^4.2. So, the only way to fix it is to do it here. I'll send a PR for this.

**Comment by GrahamCampbell** [comment]
Thanks everyone for looking into this. I think https://github.com/AltThree/Locker/pull/18 should do the job, in a way that should work on all versions, current and future. Please let me know what you think.

**Comment by blitux** [comment]
Outstanding move! I like that solution. Thanks for taking the time to fix it.
